In [3]:
import pandas as pd
import numpy as np

In [4]:
news_df = pd.read_csv("../data/processed/clean_news.csv")

In [5]:
news_df.head()

,title,text,subject,date,label,text_length
0,WOW! LEFTIST LIBRARIAN REJECTS Shipment Of Chi...,"A school librarian in Cambridge, Massachusetts...",left-news,"Sep 28, 2017",0,10062
1,Kenya opposition leader calls for calm in slum...,NAIROBI (Reuters) - Kenyan opposition leader R...,worldnews,"October 29, 2017",1,2808
2,Egypt rejects U.S. decision to move its embass...,CAIRO (Reuters) - Egypt rejected the U.S. deci...,worldnews,"December 6, 2017",1,232
3,(AUDIO)NATION OF ISLAM LEADER FARRAKHAN: “WE W...,After a recent speech given by Minister Louis ...,left-news,"May 8, 2015",0,610
4,Trump Rally Nearly Turns Into A Full-Blown Ra...,Tensions ran high outside of a campaign rally ...,News,"March 11, 2016",0,2658

In [6]:
print(news_df.shape)

(44689, 6)

In [7]:
(news_df["text"].str.strip() == "").sum()

np.int64(631)

In [8]:
news_df["text"].isnull().sum()

np.int64(0)

In [9]:
(news_df["text"] == "").sum()

np.int64(0)

In [10]:
news_df[news_df["text"].str.strip() == ""].head()

,title,text,subject,date,label,text_length
17,OUTRAGEOUS! NANCY PELOSI Claims Obamacare Hono...,,Government News,"Mar 25, 2017",0,1
27,EDUCATION SECRETARY BLOCKED And Harrassed Tryi...,,politics,"Feb 10, 2017",0,1
39,THE HORRIBLE END GAME: BERNIE SANDERS Calls fo...,,politics,"Mar 26, 2017",0,1
113,EPIC LIBERAL SMACKDOWN: “Burning Up The Street...,,politics,"Nov 13, 2016",0,1
162,MUST WATCH VIDEO! MEGYN KELLY SPELLS IT OUT FO...,,Government News,"May 9, 2015",0,1

In [11]:
news_df = news_df[news_df["text"].str.strip() != ""]

In [12]:
(news_df["text"].str.strip() == "").sum()

np.int64(0)

In [13]:
print(news_df.shape)

(44058, 6)

In [17]:
news_df.columns

Index(['title', 'text', 'subject', 'date', 'label', 'text_length', 'content'], dtype='str')

In [15]:
(news_df["title"].str.strip() == "").sum()

np.int64(0)

In [16]:
news_df["content"] = news_df["title"] + " " + news_df["text"]

In [18]:
news_df[["title", "content"]].head()

,title,content
0,WOW! LEFTIST LIBRARIAN REJECTS Shipment Of Chi...,WOW! LEFTIST LIBRARIAN REJECTS Shipment Of Chi...
1,Kenya opposition leader calls for calm in slum...,Kenya opposition leader calls for calm in slum...
2,Egypt rejects U.S. decision to move its embass...,Egypt rejects U.S. decision to move its embass...
3,(AUDIO)NATION OF ISLAM LEADER FARRAKHAN: “WE W...,(AUDIO)NATION OF ISLAM LEADER FARRAKHAN: “WE W...
4,Trump Rally Nearly Turns Into A Full-Blown Ra...,Trump Rally Nearly Turns Into A Full-Blown Ra...

In [19]:
news_df["content"] = news_df["content"].str.replace(r"\s+", " ", regex=True).str.strip()

In [20]:
news_df.to_csv("../data/processed/clean_news.csv", index=False)

In [22]:
news_df.head()

,title,text,subject,date,label,text_length,content
0,WOW! LEFTIST LIBRARIAN REJECTS Shipment Of Chi...,"A school librarian in Cambridge, Massachusetts...",left-news,"Sep 28, 2017",0,10062,WOW! LEFTIST LIBRARIAN REJECTS Shipment Of Chi...
1,Kenya opposition leader calls for calm in slum...,NAIROBI (Reuters) - Kenyan opposition leader R...,worldnews,"October 29, 2017",1,2808,Kenya opposition leader calls for calm in slum...
2,Egypt rejects U.S. decision to move its embass...,CAIRO (Reuters) - Egypt rejected the U.S. deci...,worldnews,"December 6, 2017",1,232,Egypt rejects U.S. decision to move its embass...
3,(AUDIO)NATION OF ISLAM LEADER FARRAKHAN: “WE W...,After a recent speech given by Minister Louis ...,left-news,"May 8, 2015",0,610,(AUDIO)NATION OF ISLAM LEADER FARRAKHAN: “WE W...
4,Trump Rally Nearly Turns Into A Full-Blown Ra...,Tensions ran high outside of a campaign rally ...,News,"March 11, 2016",0,2658,Trump Rally Nearly Turns Into A Full-Blown Rac...

In [23]:
print(news_df.shape)

(44058, 7)

In [24]:
news_df["label"].value_counts()

label
0    22848
1    21210
Name: count, dtype: int64

In [25]:
news_df.to_csv("../data/processed/final_news.csv", index=False)