In [1]:
!pip install transformers datasets accelerate evaluate

Requirement already satisfied: transformers in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (5.14.1)
Requirement already satisfied: datasets in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (5.0.1)
Requirement already satisfied: accelerate in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (1.14.0)
Requirement already satisfied: evaluate in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (0.4.6)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (from transformers) (1.25.1)
Requirement already satisfied: numpy>=1.17 in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (from transformers) (2.5.1)
Requirement already satisfied: packaging>=20.0 in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (from transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (from transformers) (2026.7.19)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (from transformers) (0.27.0)
Requirement already satisfied: safetensors>=0.8.0 in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (from transformers) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (from transformers) (4.70.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.32.0)
Requirement already satisfied: fsspec>=2023.5.0 in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2026.6.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.5.2)
Requirement already satisfied: httpx<1,>=0.23.0 in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.16.0)
Requirement already satisfied: colorama in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (from click<9.0.0,>=8.4.2->huggingface-hub<2.0,>=1.5.0->transformers) (0.4.6)
Requirement already satisfied: anyio in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.14.2)
Requirement already satisfied: certifi in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.7.22)
Requirement already satisfied: httpcore==1.* in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.18)
Requirement already satisfied: h11>=0.16 in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: pyarrow>=21.0.0 in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (from datasets) (24.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (from datasets) (0.4.1)
Requirement already satisfied: pandas in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (from datasets) (3.0.5)
Requirement already satisfied: requests>=2.32.2 in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (from datasets) (2.34.2)
Requirement already satisfied: xxhash in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (from datasets) (3.8.1)
Requirement already satisfied: multiprocess<0.70.20 in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (from datasets) (0.70.19)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (from fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (3.14.3)
Requirement already satisfied: psutil in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (from accelerate) (7.2.2)
Requirement already satisfied: torch>=2.0.0 in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (from accelerate) (2.11.0+cu128)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (1.24.5)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (from requests>=2.32.2->datasets) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (from requests>=2.32.2->datasets) (2.7.0)
Requirement already satisfied: setuptools<82 in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (from torch>=2.0.0->accelerate) (78.1.0)
Requirement already satisfied: sympy>=1.13.3 in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (from torch>=2.0.0->accelerate) (3.6.1)
Requirement already satisfied: jinja2 in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (from pandas->datasets) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: shellingham>=1.3.0 in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (from typer->transformers) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (from typer->transformers) (0.0.5)
Requirement already satisfied: markdown-it-py>=2.2.0 in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (from rich>=13.8.0->typer->transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (from rich>=13.8.0->typer->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in C:\Users\ankita\Desktop\AI_Powered_Fake_News_Detection\venv\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)

In [2]:
import pandas as pd
import torch

from sklearn.model_selection import train_test_split

from transformers import (
    BertTokenizer,
    BertForSequenceClassification,
    Trainer,
    TrainingArguments
)

from torch.utils.data import Dataset

In [3]:
news_df = pd.read_csv("../data/processed/final_news.csv")

In [4]:
news_df.head()

,title,text,subject,date,label,text_length,content
0,WOW! LEFTIST LIBRARIAN REJECTS Shipment Of Chi...,"A school librarian in Cambridge, Massachusetts...",left-news,"Sep 28, 2017",0,10062,WOW! LEFTIST LIBRARIAN REJECTS Shipment Of Chi...
1,Kenya opposition leader calls for calm in slum...,NAIROBI (Reuters) - Kenyan opposition leader R...,worldnews,"October 29, 2017",1,2808,Kenya opposition leader calls for calm in slum...
2,Egypt rejects U.S. decision to move its embass...,CAIRO (Reuters) - Egypt rejected the U.S. deci...,worldnews,"December 6, 2017",1,232,Egypt rejects U.S. decision to move its embass...
3,(AUDIO)NATION OF ISLAM LEADER FARRAKHAN: “WE W...,After a recent speech given by Minister Louis ...,left-news,"May 8, 2015",0,610,(AUDIO)NATION OF ISLAM LEADER FARRAKHAN: “WE W...
4,Trump Rally Nearly Turns Into A Full-Blown Ra...,Tensions ran high outside of a campaign rally ...,News,"March 11, 2016",0,2658,Trump Rally Nearly Turns Into A Full-Blown Rac...

In [5]:
print(news_df.shape)

(44058, 7)

In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    news_df["content"],
    news_df["label"],
    test_size=0.2,
    random_state=42,
    stratify=news_df["label"]
)

In [7]:
print("Training Samples:", len(X_train))
print("Testing Samples:", len(X_test))

Training Samples: 35246
Testing Samples: 8812

In [8]:
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

In [9]:
train_texts = X_train.tolist()
test_texts = X_test.tolist()

train_labels = y_train.tolist()
test_labels = y_test.tolist()

In [10]:
train_encodings = tokenizer(
    train_texts,
    truncation=True,
    padding=True,
    max_length=256
)

In [11]:
test_encodings = tokenizer(
    test_texts,
    truncation=True,
    padding=True,
    max_length=256
)

In [12]:
class NewsDataset(Dataset):

    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {
            key: torch.tensor(val[idx])
            for key, val in self.encodings.items()
        }

        item["labels"] = torch.tensor(self.labels[idx])

        return item

    def __len__(self):
        return len(self.labels)

In [13]:
train_dataset = NewsDataset(train_encodings, train_labels)

test_dataset = NewsDataset(test_encodings, test_labels)

In [14]:
print(len(train_dataset))
print(len(test_dataset))

35246
8812

In [15]:
train_dataset[0]

{'input_ids': tensor([  101,  1520,  2025,  1011, 16939,  1521,  8398,  5470,  3632,  2006,
          2847,  1011,  2146, 10474,  2743,  2102,  2055,  1520,  9152,  5620,
          1521,  1998,  1520,  8112, 19093,  1521,  1006,  1056, 28394,  3215,
          1007,  2065,  2017,  2412,  2342,  2000,  2113,  3599,  2129,  4487,
         11365,  3512,  6221,  8398,  2038,  2042,  1010,  2065,  2017,  2412,
          2342,  1037,  3819,  2742,  1010,  2017,  2123,  1056,  2342,  2000,
          2298,  2172,  2582,  2084,  6221,  8398,  1055, 10474, 17060,  1012,
          2096,  2009,  2003,  1037,  8292,  4757, 23270,  1997, 16939, 13044,
          2006,  1037,  2204,  2154,  1010,  2823,  2010,  4599,  3233,  2041,
          1998,  2028,  1997,  2068,  4240,  2004,  1037,  3819, 14764,  1997,
          2054,  1010,  3599,  2057,  2024,  2157,  2075,  2114,  1012,  2006,
          4465,  1010,  8398, 23678,  2098,  2055,  2010,  8599,  1999,  1037,
          7143,  3947,  2000, 15886,  2013,  1996,  2755,  2008,  2053,  2028,
          3662,  2039,  2000,  2010,  2283,  2006,  5958,  1012, 10166,  1010,
          2547,  8599,  2074,  2041,  1024,  2861,  2454,  2111,  3427,  1996,
         17331,  1010,  2340,  2454,  2062,  2084,  1996,  2200,  2204,  8599,
          2013,  1018,  2086,  3283,   999,  6221,  1046,  1012,  8398,  1006,
          1030,  2613,  5280, 19058, 24456,  2361,  1007,  2254,  2570,  1010,
          2418,  4168,  3388,  5529, 22320,  7474,  1012,  5529,  2787,  2000,
          2404,  2006,  2010,  2317,  1011, 21592,  2645,  8177,  1998,  5376,
          2000,  1996,  6221,  1055,  3639,  2004,  9428,  1996,  2878,  2088,
          2001,  2437,  4569,  1997,  2256, 16405,  4757, 17643, 29325,  1011,
          1999,  1011,  2708,  1012,  1999,  3433,  2000, 11476,  6256,  1997,
          1996,  6221,  1010, 22320,  7474,  2292,  3071,  2113,  2008,  2382,
          2454,  4841,  2074,  2359,  2000,  2156, 13857,  1998,  9393,  1006,
          2040,  2003,  1037,  2158,  1010,   102]),
 'token_type_ids': tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 'attention_mask': tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 'labels': tensor(0)}

In [16]:
model = BertForSequenceClassification.from_pretrained(
    "bert-base-uncased",
    num_labels=2
)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [17]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cuda

In [18]:
model.to(device)

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (pooler): BertPooler(
      (dense): Linear(in_features=768, out_features=768, bias=True)
      (activation): Tanh()
    )
  )
  (dropout): Dropout(p=0.1, inplace=False)
  (classifier): Linear(in_features=768, out_features=2, bias=True)
)

In [19]:
print(next(model.parameters()).device)

cuda:0

In [20]:
import transformers
print(transformers.__version__)

5.14.1

In [21]:
training_args = TrainingArguments(
    output_dir="../results",
    num_train_epochs=2,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    learning_rate=2e-5,
    weight_decay=0.01,
    logging_steps=100,
    save_strategy="epoch",
    eval_strategy="epoch",
    report_to="none",
    fp16=True
)

In [22]:
print(training_args)

TrainingArguments(
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=None,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_static_graph=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
enable_jit_checkpoint=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=True,
fp16_full_eval=False,
fsdp=None,
fsdp_config=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=None,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_num_input_tokens_seen=no,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=2e-05,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=False,
local_rank=-1,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=None,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=100,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs=None,
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=None,
neftune_noise_alpha=None,
num_train_epochs=2,
optim=OptimizerNames.ADAMW_TORCH_FUSED,
optim_args=None,
optim_target_modules=None,
output_dir=../results,
parallelism_config=None,
per_device_eval_batch_size=4,
per_device_train_batch_size=4,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
trackio_bucket_id=None,
trackio_space_id=None,
trackio_static_space_id=None,
train_sampling_strategy=random,
use_cache=False,
use_cpu=False,
use_liger_kernel=False,
warmup_ratio=None,
warmup_steps=0,
weight_decay=0.01,
)

In [23]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset
)

In [24]:
print(trainer.args.per_device_train_batch_size)
print(trainer.args.num_train_epochs)

4
2

In [25]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model.to(device)

print(device)

cuda

In [26]:
trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=17624, training_loss=0.006290808404595864, metrics={'train_runtime': 34561.5907, 'train_samples_per_second': 2.04, 'train_steps_per_second': 0.51, 'total_flos': 9273612257218560.0, 'train_loss': 0.006290808404595864, 'epoch': 2.0})

In [27]:
model.save_pretrained("../models/fake_news_bert")
tokenizer.save_pretrained("../models/fake_news_bert")

print("Model Saved Successfully!")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model Saved Successfully!